name: Test | Cypress - Linux
run-name: 🚀 Test | Cypress - Linux - ${{github.ref_name}} by @${{ github.actor }}

#######################################################
# Version: 1.0.0
#######################################################
# TODO: Add notification mechanism for completion of the test.
# TODO: Add notification mechanism on fail/success.
# TODO: Save results as artifacts.
# TODO: Optimize packages.
#######################################################
# Setup
# 1. Create required environments/secrets in the repository.
# 2. Setup secrets and variables for them.
# 3. Run pipeline.
#######################################################

on:
  # push:
  #   branches: [ "master", "main" ]
  # pull_request:
  #   branches: [ "main", "main" ]
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: 'Node Version'
        default: '20.7.0'
        required: false
      firefoxVersion:
        description: 'Firefox Version'
        default: '121.0'
        required: false
      edgeVersion:
        description: 'Edge Version'
        default: 'stable'
        required: false
      chromeVersion:
        description: 'Chrome Version'
        default: 'stable'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PROJECT_FOLDER }}
    strategy:
      fail-fast: false
      matrix:
        driver: ['Firefox', 'Chrome', 'Edge']
        resolution: ['1024x768', '1920x1080']
    env:
      NODE_VERSION: ${{ github.event.inputs.nodeVersion }}
      FIREFOX_VERSION: ${{ github.event.inputs.firefoxVersion }}
      EDGE_VERSION: ${{ github.event.inputs.edgeVersion }}
      CHROME_VERSION: ${{ github.event.inputs.chromeVersion }}
      PROJECT_FOLDER: "./typescript/cypress"

    steps:

      - name: Setup repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4   
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: ${{ env.PROJECT_FOLDER }}/package-lock.json
          cache: 'npm'

      - name: Setup Chrome
        if: contains(matrix.driver, 'Chrome')
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ env.CHROME_VERSION }}

      - name: Setup Firefox
        if: contains(matrix.driver, 'Firefox')
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ env.FIREFOX_VERSION }}

      - name: Setup Edge
        if: contains(matrix.driver, 'Edge')
        uses: browser-actions/setup-edge@latest
        with:
          edge-version: ${{ env.EDGE_VERSION }}

      - name: Setup Chrome
        if: contains(matrix.driver, 'Chrome')
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ env.CHROME_VERSION }}

      - name: Setup Firefox
        if: contains(matrix.driver, 'Firefox')
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ env.FIREFOX_VERSION }}

      - name: Setup Edge
        if: contains(matrix.driver, 'Edge')
        uses: browser-actions/setup-edge@latest
        with:
          edge-version: ${{ env.EDGE_VERSION }}

      - name: Check pre-requisites - Firefox
        if: contains(matrix.driver, 'Firefox')
        run: |
          firefox --version

      - name: Check pre-requisites - Chrome
        if: contains(matrix.driver, 'Chrome')
        run: |
          chrome --version

      - name: Check pre-requisites - Edge
        if: contains(matrix.driver, 'Edge')
        run: |
          microsoft-edge --version

      - name: Check pre-requisites - generic
        run: |
          uname -a
          cat /etc/*release
          python3 --version
          pip --version

      - name: Install dependencies
        run: |
          npm i

      - name: Run tests
        run: |
          IFS='x' read -ra RES <<< "${{ matrix.resolution }}"
          export CFG_DRIVER_NAME=${{ matrix.driver }}
          export CFG_DRIVER_WIDTH=${RES[0]}
          export CFG_DRIVER_HEIGHT=${RES[1]}
          npm run cypress:run
